version: "3.8"
services:
  server:
    image: appscrap
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/employeedb?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=scrap
      - MYSQL_USER=spring_user
      - MYSQL_PASSWORD=root

networks:
  springmysql-net: