version: "3.8"
services:
  server:
    image: appscrap
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/scrap?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=scrap
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

networks:
  springmysql-net: